# Generated by Django 4.1.9 on 2023-06-20 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_dataset_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinneddataset",
            name="date_pinned",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date pinned"
            ),
        ),
        migrations.AddField(
            model_name="pinneditem",
            name="date_pinned",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date pinned"
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="last_modified",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last modified"
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="public",
            field=models.BooleanField(default=False, verbose_name="public"),
        ),
    ]
