# Generated by Django 4.1.9 on 2023-07-05 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_collection_url_item_collections_item_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date added"
            ),
        ),
    ]
