# Generated by Django 4.1.9 on 2023-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_collection_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="url",
            field=models.URLField(
                blank=True, default="", max_length=300, verbose_name="url"
            ),
        ),
    ]
