# Generated by Django 4.1.9 on 2023-07-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_dataset_search_paremeters"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="sites",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="title"
            ),
        ),
    ]
