# Generated by Django 4.1.9 on 2023-07-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_collection_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="url"
            ),
        ),
    ]
