# Generated by Django 4.1.9 on 2023-07-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_dataset_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="creator",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="creator"
            ),
        ),
    ]
