# Generated by Django 4.1.9 on 2023-07-08 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_item_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="created_by",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
