# Generated by Django 4.1.9 on 2023-07-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_item_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="text",
            new_name="title",
        ),
    ]
