# Generated by Django 4.1.9 on 2023-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_alter_dataset_removed_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=500, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=500, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="tag"
            ),
        ),
    ]
