# Generated by Django 4.1.9 on 2023-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_alter_collection_title_alter_customuser_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="contributor",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="contributor"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="coverage",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="coverage"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="format",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="format"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="language",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="language"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="publisher",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="publisher"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="relation",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="relation"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rights",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="rights"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="source",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="source"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="subject",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="subject"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="date",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_id",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="item ID",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="type"
            ),
        ),
    ]
