LIST = {
'marccountry': # MARC_COUNTRY_CODE_DICT
{
'aa': 'Asia',
'abc': 'Afghanistan',
'ac': 'Armenia (Republic)',
'aca': 'Azerbaijan',
'ae': 'Bahrain',
'af': 'Bangladesh',
'ag': 'Borneo',
'ai': 'Burma',
'ai': 'Bhutan',
'air': 'Brunei',
'aj': 'Cambodia',
'ajr': 'China',
'aku': 'Anhui Sheng (China)',
'alu': 'Zhejiang Sheng (China)',
'am': 'Chongqing (China)',
'an': 'Fujian Sheng (China)',
'ao': 'Hainan Sheng (China)',
'aq': 'Heilongjiang Sheng (China)',
'aru': 'Hubei Sheng (China)',
'as': 'Hong Kong (China)',
'at': 'Henan Sheng (China)',
'au': 'Hebei Sheng (China)',
'aw': 'Hunan Sheng (China)',
'ay': 'Inner Mongolia (China)',
'azu': 'Gansu Sheng (China)',
'ba': 'Guangxi Zhuangzu Zizhiqu (China)',
'bb': 'Jiangxi Sheng (China)',
'bcc': 'Guangdong Sheng (China)',
'bd': 'Jilin Sheng (China)',
'be': 'Jiangsu Sheng (China)',
'bf': 'Guizhou Sheng (China)',
'bg': 'Liaoning Sheng (China)',
'bh': 'Macau (China : Special Administrative Region)',
'bi': 'Ningxia Huizu Zizhiqu (China)',
'bl': 'Beijing (China)',
'bm': 'shanxi Sheng (China)',
'bn': 'shanghai (China)',
'bo': 'shandong Sheng (China)',
'bp': 'shaanxi Sheng (China)',
'br': 'Xinjiang Uygur Zizhiqu (China)',
'bs': 'sichuan Sheng (China)',
'bt': 'Tibet (China)',
'bu': 'Tianjin (China)',
'bv': 'Qinghai Sheng (China)',
'bw': 'Yunnan Sheng (China)',
'bwr': 'Yangtze River (China)',
'bx': 'Kunlun Mountains (China and India)',
'ca': 'Bo Hai (China)',
'cau': 'Xi River (China)',
'cb': 'Yellow River (China)',
'cc': 'sri Lanka',
'cd': 'Taiwan',
'ce': 'Cyprus',
'cf': 'Timor-Leste',
'cg': 'Georgia (Republic)',
'ch': 'Hong Kong',
'ci': 'India',
'cj': 'Indonesia',
'ck': 'Iraq',
'cl': 'Iran',
'cm': 'Israel',
'cn': 'Japan',
'co': 'Jordan',
'cou': 'Kyrgyzstan',
'cp': 'Korea (North)',
'cq': 'Korea (South)',
'cr': 'Korea',
'cs': 'Kuwait',
'ctu': 'Kazakhstan',
'cu': 'Lebanon',
'cv': 'Laos',
'cw': 'Macao',
'cx': 'Oman',
'cy': 'Mongolia',
'cz': 'Malaysia',
'dcu': 'Nepal',
'deu': 'New Guinea',
'dk': 'Okinawa',
'dm': 'Philippines',
'dq': 'Pakistan',
'dr': 'Papua New Guinea',
'ea': 'Portuguese Timor',
'ec': 'Qatar',
'eg': 'singapore',
'em': 'sikkim',
'enk': 'saudi Arabia',
'er': 'syria',
'err': 'Tajikistan',
'es': 'Thailand',
'et': 'Turkmenistan',
'fa': 'United Arab Emirates',
'fg': 'Turkey',
'fi': 'Uzbekistan',
'fj': 'Viet Nam, North',
'fk': 'Viet Nam, South',
'flu': 'Vietnam',
'fm': 'Yemen (Republic)',
'fp': 'Yemen (People\'s Democratic Republic)',
'fr': 'Amur River (China and Russia)',
'fs': 'Bengal, Bay of',
'ft': 'Asia, Central',
'gau': 'East Asia',
'gb': 'Thailand, Gulf of',
'gd': 'Mekong River',
'ge': 'Himalaya Mountains',
'gg': 'Indochina',
'gh': 'Caspian Sea',
'gi': 'Malaya',
'gl': 'East China Sea',
'gm': 'south China Sea',
'gn': 'Paracel Islands',
'go': 'spratly Islands',
'gp': 'Persian Gulf',
'gr': 'Arabian Peninsula',
'gs': 'southeast Asia',
'gsr': 'Tien Shan',
'gt': 'Arabian Sea',
'gu': 'Middle East',
'gv': 'West Bank',
'gw': 'Gaza Strip',
'gy': 'Israel-Syria Demilitarized Zones',
'gz': 'Israel-Jordan Demilitarized Zones',
'hiu': 'Iraq-Saudi Arabia Neutral Zone',
'hk': 'Yellow Sea',
'hm': 'south Asia',
'ho': 'Commonwealth countries',
'ht': 'Intercontinental areas (Western Hemisphere)',
'hu': 'Caribbean Area; Caribbean Sea',
'iau': 'Latin America',
'ic': 'Middle America',
'idu': 'Circumcaribbean',
'ie': 'Developing countries',
'ii': 'Developed countries',
'ilu': 'Europe',
'im': 'Albania',
'inu': 'Andorra',
'io': 'Austria',
'iq': 'Belgium',
'ir': 'Bosnia and Herzegovina',
'is': 'Bulgaria',
'it': 'Belarus',
'iu': 'Croatia',
'iv': 'Czechoslovakia',
'iw': 'Denmark',
'iy': 'Estonia',
'ja': 'Finland',
'je': 'France',
'ji': 'Germany (East)',
'jm': 'Guernsey',
'jn': 'Gibraltar',
'jo': 'Greece',
'ke': 'Germany (West)',
'kg': 'Germany',
'kgr': 'Hungary',
'kn': 'Iceland',
'ko': 'Ireland',
'ksu': 'Isle of Man',
'ku': 'Italy',
'kv': 'Jersey',
'kyu': 'Kosovo',
'kz': 'Liechtenstein',
'kzr': 'Lithuania',
'lau': 'Luxembourg',
'lb': 'Latvia',
'le': 'Monaco',
'lh': 'Malta',
'li': 'Montenegro',
'lir': 'Moldova',
'ln': 'Netherlands',
'lo': 'Norway',
'ls': 'Poland',
'lu': 'Portugal',
'lv': 'serbia',
'lvr': 'Romania',
'ly': 'Russia (Federation)',
'mau': 'san Marino',
'mbc': 'spain',
'mc': 'sweden',
'mdu': 'switzerland',
'meu': 'Great Britain',
'mf': 'England',
'mg': 'Northern Ireland',
'mh': 'scotland',
'miu': 'Great Britain Miscellaneous Island Dependencies',
'mj': 'Wales',
'mk': 'Ukraine',
'ml': 'Russia. Russian Empire. Soviet Union. Former Soviet Republics',
'mm': 'Armenia (Republic)',
'mnu': 'Azerbaijan',
'mo': 'Belarus',
'mou': 'Estonia',
'mp': 'Georgia (Republic)',
'mq': 'Kyrgyzstan',
'mr': 'Kazakhstan',
'msu': 'Lithuania',
'mtu': 'Latvia',
'mu': 'Moldova',
'mv': 'Russia (Federation)',
'mvr': 'Tajikistan',
'mw': 'Turkmenistan',
'mx': 'Ukraine',
'my': 'Uzbekistan',
'mz': 'Central Chernozem Region (Russia)',
'na': 'siberia, Eastern (Russia)',
'nbu': 'Russian Far East (Russia)',
'ncu': 'Caucasus',
'ndu': 'Central Region, RSFSR',
'ne': 'soviet Union, Northwestern',
'nfc': 'soviet Central Asia',
'ng': 'Volga River (Russia)',
'nhu': 'Caucasus, Northern (Russia)',
'nik': 'siberia (Russia)',
'nju': 'Ural Mountains (Russia)',
'nkc': 'Volgo-Viatskii Region, RSFSR',
'nl': 'siberia, Western (Russia)',
'nm': 'Vatican City',
'nmu': 'North Macedonia',
'nn': 'slovakia',
'no': 'Czech Republic',
'np': 'slovenia',
'nq': 'serbia and Montenegro; Yugoslavia',
'nr': 'Alps',
'nsc': 'Baltic States',
'ntc': 'Europe, Central',
'nu': 'Balkan Peninsula',
'nuc': 'Europe, Eastern',
'nvu': 'Iberian Peninsula',
'nw': 'Benelux countries',
'nx': 'Europe, Northern',
'nyu': 'Danube River',
'nz': 'Pyrenees',
'ohu': 'Rhine River',
'oku': 'Europe, Southern',
'onc': 'Europe, East Central',
'oru': 'scandinavia',
'ot': 'Europe, Western',
'pau': 'Africa',
'pc': 'Algeria',
'pe': 'Angola',
'pf': 'Burundi',
'pg': 'Botswana',
'ph': 'Biafra',
'pic': 'Chad',
'pk': 'Congo (Brazzaville)',
'pl': 'Congo (Democratic Republic)',
'pn': 'Cameroon',
'po': 'Central African Republic',
'pp': 'Benin',
'pr': 'Eritrea',
'pt': 'Equatorial Guinea',
'pw': 'Ethiopia',
'py': 'Djibouti',
'qa': 'Ghana',
'qea': 'Gambia',
'quc': 'Gabon',
'rb': 'Guinea',
're': 'Ifni',
'rh': 'Côte d\'Ivoire',
'riu': 'Kenya',
'rm': 'Liberia',
'ru': 'Lesotho',
'rur': 'Libya',
'rw': 'Madagascar',
'ry': 'Mali',
'sa': 'Morocco',
'sb': 'Mauritania',
'sc': 'Malawi',
'scu': 'Mozambique',
'sd': 'Niger',
'sdu': 'Nigeria',
'se': 'Guinea-Bissau',
'sf': 'Zimbabwe',
'sg': 'Rwanda',
'sh': 'south Africa',
'si': 'south Sudan',
'sj': 'sao Tome and Principe',
'sk': 'senegal',
'sl': 'spanish North Africa',
'sm': 'sudan',
'sn': 'sierra Leone',
'snc': 'somalia',
'so': 'Eswatini',
'sp': 'Western Sahara',
'sq': 'Namibia',
'sr': 'Togo',
'ss': 'Tunisia',
'st': 'Tanzania',
'stk': 'Egypt',
'su': 'Uganda',
'sv': 'Burkina Faso',
'sw': 'Zambia',
'sx': 'Atlas Mountains',
'sy': 'Africa, Sub-Saharan',
'sz': 'Africa, Central',
'ta': 'sahara',
'tar': 'Africa, Eastern',
'tc': 'Africa, North',
'tg': 'Congo River',
'th': 'Africa, Northeast',
'ti': 'Niger River',
'tk': 'Nile River',
'tkr': 'sudan (Region)',
'tl': 'Africa, French-speaking Equatorial',
'tma': 'Great Rift Valley',
'tnu': 'Africa, Southern',
'to': 'suez Canal (Egypt)',
'tr': 'Volta River (Ghana)',
'ts': 'Africa, West',
'tt': 'Zambezi River',
'tu': 'French Community',
'tv': 'Indian Ocean',
'txu': 'British Indian Ocean Territory',
'tz': 'Comoros',
'ua': 'Terres australes et antarctiques françaises',
'uc': 'Heard and McDonald Islands',
'ug': 'Mauritius',
'ui': 'Mayotte',
'uik': 'Réunion',
'uk': 'seychelles',
'un': 'Christmas Island (Indian Ocean)',
'unr': 'Cocos (Keeling) Islands',
'up': 'Maldives',
'ur': 'socotra Island',
'us': 'Atlantic Ocean',
'utu': 'North Atlantic Ocean',
'uv': 'Azores',
'uy': 'Bermuda Islands',
'uz': 'Canary Islands',
'uzr': 'Cabo Verde',
'vau': 'Faroe Islands',
'vb': 'Jan Mayen Island',
'vc': 'Madeira Islands',
've': 'svalbard (Norway)',
'vi': 'south Atlantic Ocean',
'vm': 'Ascension Island (Atlantic Ocean)',
'vn': 'Bouvet Island',
'vp': 'Falkland Islands',
'vra': 'Tristan da Cunha',
'vs': 'saint Helena',
'vtu': 'south Georgia and South Sandwich Islands',
'wau': 'Intercontinental areas (Eastern Hemisphere)',
'wb': 'Arab countries',
'wea': 'Black Sea',
'wf': 'Eurasia',
'wiu': 'Mediterranean Region; Mediterranean Sea',
'wj': 'Red Sea',
'wk': 'North America',
'wlk': 'Canada',
'ws': 'Alberta',
'wvu': 'British Columbia',
'wyu': 'Manitoba',
'xa': 'Newfoundland and Labrador',
'xb': 'New Brunswick',
'xc': 'Nova Scotia',
'xd': 'Northwest Territories',
'xe': 'Nunavut',
'xf': 'Ontario',
'xga': 'Prince Edward Island',
'xh': 'Québec (Province)',
'xi': 'saskatchewan',
'xj': 'Yukon Territory',
'xk': 'Hudson Bay',
'xl': 'Maritime Provinces',
'xm': 'Prairie Provinces',
'xn': 'Greenland',
'xna': 'Mexico',
'xo': 'United States',
'xoa': 'Alaska',
'xp': 'Alabama',
'xr': 'Arkansas',
'xra': 'Arizona',
'xs': 'California',
'xv': 'Colorado',
'xx': 'Connecticut',
'xxc': 'Washington (D.C.)',
'xxk': 'Delaware',
'xxr': 'Florida',
'xxu': 'Georgia',
'ye': 'Hawaii',
'ykc': 'Iowa',
'ys': 'Idaho',
'yu': 'Illinois',
'za': 'Indiana',
},
'marcgac': # MARC_GEOGRAPHIC_AREAS_CODE_DICT
{
'a': 'Asia',
'a-af': 'Afghanistan',
'a-ai': 'Armenia (Republic)',
'a-aj': 'Azerbaijan',
'a-ba': 'Bahrain',
'a-bg': 'Bangladesh',
'a-bn': 'Borneo',
'a-br': 'Burma',
'a-bt': 'Bhutan',
'a-bx': 'Brunei',
'a-cb': 'Cambodia',
'a-cc': 'China',
'a-cc-an': 'Anhui Sheng (China)',
'a-cc-ch': 'Zhejiang Sheng (China)',
'a-cc-cq': 'Chongqing (China)',
'a-cc-fu': 'Fujian Sheng (China)',
'a-cc-ha': 'Hainan Sheng (China)',
'a-cc-he': 'Heilongjiang Sheng (China)',
'a-cc-hh': 'Hubei Sheng (China)',
'a-cc-hk': 'Hong Kong (China)',
'a-cc-ho': 'Henan Sheng (China)',
'a-cc-hp': 'Hebei Sheng (China)',
'a-cc-hu': 'Hunan Sheng (China)',
'a-cc-im': 'Inner Mongolia (China)',
'a-cc-ka': 'Gansu Sheng (China)',
'a-cc-kc': 'Guangxi Zhuangzu Zizhiqu (China)',
'a-cc-ki': 'Jiangxi Sheng (China)',
'a-cc-kn': 'Guangdong Sheng (China)',
'a-cc-kr': 'Jilin Sheng (China)',
'a-cc-ku': 'Jiangsu Sheng (China)',
'a-cc-kw': 'Guizhou Sheng (China)',
'a-cc-lp': 'Liaoning Sheng (China)',
'a-cc-mh': 'Macau (China : Special Administrative Region)',
'a-cc-nn': 'Ningxia Huizu Zizhiqu (China)',
'a-cc-pe': 'Beijing (China)',
'a-cc-sh': 'shanxi Sheng (China)',
'a-cc-sm': 'shanghai (China)',
'a-cc-sp': 'shandong Sheng (China)',
'a-cc-ss': 'shaanxi Sheng (China)',
'a-cc-su': 'Xinjiang Uygur Zizhiqu (China)',
'a-cc-sz': 'sichuan Sheng (China)',
'a-cc-ti': 'Tibet (China)',
'a-cc-tn': 'Tianjin (China)',
'a-cc-ts': 'Qinghai Sheng (China)',
'a-cc-yu': 'Yunnan Sheng (China)',
'a-ccg': 'Yangtze River (China)',
'a-cck': 'Kunlun Mountains (China and India)',
'a-ccp': 'Bo Hai (China)',
'a-ccs': 'Xi River (China)',
'a-ccy': 'Yellow River (China)',
'a-ce': 'sri Lanka',
'a-ch': 'Taiwan',
'a-cy': 'Cyprus',
'a-em': 'Timor-Leste',
'a-gs': 'Georgia (Republic)',
'a-hk': 'Hong Kong',
'a-ii': 'India',
'a-io': 'Indonesia',
'a-iq': 'Iraq',
'a-ir': 'Iran',
'a-is': 'Israel',
'a-ja': 'Japan',
'a-jo': 'Jordan',
'a-kg': 'Kyrgyzstan',
'a-kn': 'Korea (North)',
'a-ko': 'Korea (South)',
'a-kr': 'Korea',
'a-ku': 'Kuwait',
'a-kz': 'Kazakhstan',
'a-le': 'Lebanon',
'a-ls': 'Laos',
'a-mh': 'Macao',
'a-mk': 'Oman',
'a-mp': 'Mongolia',
'a-my': 'Malaysia',
'a-np': 'Nepal',
'a-nw': 'New Guinea',
'a-ok': 'Okinawa',
'a-ph': 'Philippines',
'a-pk': 'Pakistan',
'a-pp': 'Papua New Guinea',
'a-pt': 'Portuguese Timor',
'a-qa': 'Qatar',
'a-si': 'singapore',
'a-sk': 'sikkim',
'a-su': 'saudi Arabia',
'a-sy': 'syria',
'a-ta': 'Tajikistan',
'a-th': 'Thailand',
'a-tk': 'Turkmenistan',
'a-ts': 'United Arab Emirates',
'a-tu': 'Turkey',
'a-uz': 'Uzbekistan',
'a-vn': 'Viet Nam, North',
'a-vs': 'Viet Nam, South',
'a-vt': 'Vietnam',
'a-ye': 'Yemen (Republic)',
'a-ys': 'Yemen (People\'s Democratic Republic)',
'aa': 'Amur River (China and Russia)',
'ab': 'Bengal, Bay of',
'ac': 'Asia, Central',
'ae': 'East Asia',
'af': 'Thailand, Gulf of',
'ag': 'Mekong River',
'ah': 'Himalaya Mountains',
'ai': 'Indochina',
'ak': 'Caspian Sea',
'am': 'Malaya',
'an': 'East China Sea',
'ao': 'south China Sea',
'aopf': 'Paracel Islands',
'aoxp': 'spratly Islands',
'ap': 'Persian Gulf',
'ar': 'Arabian Peninsula',
'as': 'southeast Asia',
'at': 'Tien Shan',
'au': 'Arabian Sea',
'aw': 'Middle East',
'awba': 'West Bank',
'awgz': 'Gaza Strip',
'awiu': 'Israel-Syria Demilitarized Zones',
'awiw': 'Israel-Jordan Demilitarized Zones',
'awiy': 'Iraq-Saudi Arabia Neutral Zone',
'ay': 'Yellow Sea',
'az': 'south Asia',
'b': 'Commonwealth countries',
'c': 'Intercontinental areas (Western Hemisphere)',
'cc': 'Caribbean Area; Caribbean Sea',
'cl': 'Latin America',
'cm': 'Middle America',
'cr': 'Circumcaribbean',
'd': 'Developing countries',
'dd': 'Developed countries',
'e': 'Europe',
'e-aa': 'Albania',
'e-an': 'Andorra',
'e-au': 'Austria',
'e-be': 'Belgium',
'e-bn': 'Bosnia and Herzegovina',
'e-bu': 'Bulgaria',
'e-bw': 'Belarus',
'e-ci': 'Croatia',
'e-cs': 'Czechoslovakia',
'e-dk': 'Denmark',
'e-er': 'Estonia',
'e-fi': 'Finland',
'e-fr': 'France',
'e-ge': 'Germany (East)',
'e-gg': 'Guernsey',
'e-gi': 'Gibraltar',
'e-gr': 'Greece',
'e-gw': 'Germany (West)',
'e-gx': 'Germany',
'e-hu': 'Hungary',
'e-ic': 'Iceland',
'e-ie': 'Ireland',
'e-im': 'Isle of Man',
'e-it': 'Italy',
'e-je': 'Jersey',
'e-kv': 'Kosovo',
'e-lh': 'Liechtenstein',
'e-li': 'Lithuania',
'e-lu': 'Luxembourg',
'e-lv': 'Latvia',
'e-mc': 'Monaco',
'e-mm': 'Malta',
'e-mo': 'Montenegro',
'e-mv': 'Moldova',
'e-ne': 'Netherlands',
'e-no': 'Norway',
'e-pl': 'Poland',
'e-po': 'Portugal',
'e-rb': 'serbia',
'e-rm': 'Romania',
'e-ru': 'Russia (Federation)',
'e-sm': 'san Marino',
'e-sp': 'spain',
'e-sw': 'sweden',
'e-sz': 'switzerland',
'e-uk': 'Great Britain',
'e-uk-en': 'England',
'e-uk-ni': 'Northern Ireland',
'e-uk-st': 'scotland',
'e-uk-ui': 'Great Britain Miscellaneous Island Dependencies',
'e-uk-wl': 'Wales',
'e-un': 'Ukraine',
'e-ur': 'Russia. Russian Empire. Soviet Union. Former Soviet Republics',
'e-ur-ai': 'Armenia (Republic)',
'e-ur-aj': 'Azerbaijan',
'e-ur-bw': 'Belarus',
'e-ur-er': 'Estonia',
'e-ur-gs': 'Georgia (Republic)',
'e-ur-kg': 'Kyrgyzstan',
'e-ur-kz': 'Kazakhstan',
'e-ur-li': 'Lithuania',
'e-ur-lv': 'Latvia',
'e-ur-mv': 'Moldova',
'e-ur-ru': 'Russia (Federation)',
'e-ur-ta': 'Tajikistan',
'e-ur-tk': 'Turkmenistan',
'e-ur-un': 'Ukraine',
'e-ur-uz': 'Uzbekistan',
'e-urc': 'Central Chernozem Region (Russia)',
'e-ure': 'siberia, Eastern (Russia)',
'e-urf': 'Russian Far East (Russia)',
'e-urk': 'Caucasus',
'e-url': 'Central Region, RSFSR',
'e-urn': 'soviet Union, Northwestern',
'e-uro': 'soviet Central Asia',
'e-urp': 'Volga River (Russia)',
'e-urr': 'Caucasus, Northern (Russia)',
'e-urs': 'siberia (Russia)',
'e-uru': 'Ural Mountains (Russia)',
'e-urv': 'Volgo-Viatskii Region, RSFSR',
'e-urw': 'siberia, Western (Russia)',
'e-vc': 'Vatican City',
'e-xn': 'North Macedonia',
'e-xo': 'slovakia',
'e-xr': 'Czech Republic',
'e-xv': 'slovenia',
'e-yu': 'serbia and Montenegro; Yugoslavia',
'ea': 'Alps',
'eb': 'Baltic States',
'ec': 'Europe, Central',
'ed': 'Balkan Peninsula',
'ee': 'Europe, Eastern',
'ei': 'Iberian Peninsula',
'el': 'Benelux countries',
'en': 'Europe, Northern',
'eo': 'Danube River',
'ep': 'Pyrenees',
'er': 'Rhine River',
'es': 'Europe, Southern',
'et': 'Europe, East Central',
'ev': 'scandinavia',
'ew': 'Europe, Western',
'f': 'Africa',
'f-ae': 'Algeria',
'f-ao': 'Angola',
'f-bd': 'Burundi',
'f-bs': 'Botswana',
'f-by': 'Biafra',
'f-cd': 'Chad',
'f-cf': 'Congo (Brazzaville)',
'f-cg': 'Congo (Democratic Republic)',
'f-cm': 'Cameroon',
'f-cx': 'Central African Republic',
'f-dm': 'Benin',
'f-ea': 'Eritrea',
'f-eg': 'Equatorial Guinea',
'f-et': 'Ethiopia',
'f-ft': 'Djibouti',
'f-gh': 'Ghana',
'f-gm': 'Gambia',
'f-go': 'Gabon',
'f-gv': 'Guinea',
'f-if': 'Ifni',
'f-iv': 'Côte d\'Ivoire',
'f-ke': 'Kenya',
'f-lb': 'Liberia',
'f-lo': 'Lesotho',
'f-ly': 'Libya',
'f-mg': 'Madagascar',
'f-ml': 'Mali',
'f-mr': 'Morocco',
'f-mu': 'Mauritania',
'f-mw': 'Malawi',
'f-mz': 'Mozambique',
'f-ng': 'Niger',
'f-nr': 'Nigeria',
'f-pg': 'Guinea-Bissau',
'f-rh': 'Zimbabwe',
'f-rw': 'Rwanda',
'f-sa': 'south Africa',
'f-sd': 'south Sudan',
'f-sf': 'sao Tome and Principe',
'f-sg': 'senegal',
'f-sh': 'spanish North Africa',
'f-sj': 'sudan',
'f-sl': 'sierra Leone',
'f-so': 'somalia',
'f-sq': 'Eswatini',
'f-ss': 'Western Sahara',
'f-sx': 'Namibia',
'f-tg': 'Togo',
'f-ti': 'Tunisia',
'f-tz': 'Tanzania',
'f-ua': 'Egypt',
'f-ug': 'Uganda',
'f-uv': 'Burkina Faso',
'f-za': 'Zambia',
'fa': 'Atlas Mountains',
'fb': 'Africa, Sub-Saharan',
'fc': 'Africa, Central',
'fd': 'sahara',
'fe': 'Africa, Eastern',
'ff': 'Africa, North',
'fg': 'Congo River',
'fh': 'Africa, Northeast',
'fi': 'Niger River',
'fl': 'Nile River',
'fn': 'sudan (Region)',
'fq': 'Africa, French-speaking Equatorial',
'fr': 'Great Rift Valley',
'fs': 'Africa, Southern',
'fu': 'suez Canal (Egypt)',
'fv': 'Volta River (Ghana)',
'fw': 'Africa, West',
'fz': 'Zambezi River',
'h': 'French Community',
'i': 'Indian Ocean',
'i-bi': 'British Indian Ocean Territory',
'i-cq': 'Comoros',
'i-fs': 'Terres australes et antarctiques françaises',
'i-hm': 'Heard and McDonald Islands',
'i-mf': 'Mauritius',
'i-my': 'Mayotte',
'i-re': 'Réunion',
'i-se': 'seychelles',
'i-xa': 'Christmas Island (Indian Ocean)',
'i-xb': 'Cocos (Keeling) Islands',
'i-xc': 'Maldives',
'i-xo': 'socotra Island',
'l': 'Atlantic Ocean',
'ln': 'North Atlantic Ocean',
'lnaz': 'Azores',
'lnbm': 'Bermuda Islands',
'lnca': 'Canary Islands',
'lncv': 'Cabo Verde',
'lnfa': 'Faroe Islands',
'lnjn': 'Jan Mayen Island',
'lnma': 'Madeira Islands',
'lnsb': 'svalbard (Norway)',
'ls': 'south Atlantic Ocean',
'lsai': 'Ascension Island (Atlantic Ocean)',
'lsbv': 'Bouvet Island',
'lsfk': 'Falkland Islands',
'lstd': 'Tristan da Cunha',
'lsxj': 'saint Helena',
'lsxs': 'south Georgia and South Sandwich Islands',
'm': 'Intercontinental areas (Eastern Hemisphere)',
'ma': 'Arab countries',
'mb': 'Black Sea',
'me': 'Eurasia',
'mm': 'Mediterranean Region; Mediterranean Sea',
'mr': 'Red Sea',
'n': 'North America',
'n-cn': 'Canada',
'n-cn-ab': 'Alberta',
'n-cn-bc': 'British Columbia',
'n-cn-mb': 'Manitoba',
'n-cn-nf': 'Newfoundland and Labrador',
'n-cn-nk': 'New Brunswick',
'n-cn-ns': 'Nova Scotia',
'n-cn-nt': 'Northwest Territories',
'n-cn-nu': 'Nunavut',
'n-cn-on': 'Ontario',
'n-cn-pi': 'Prince Edward Island',
'n-cn-qu': 'Québec (Province)',
'n-cn-sn': 'saskatchewan',
'n-cn-yk': 'Yukon Territory',
'n-cnh': 'Hudson Bay',
'n-cnm': 'Maritime Provinces',
'n-cnp': 'Prairie Provinces',
'n-gl': 'Greenland',
'n-mx': 'Mexico',
'n-us': 'United States',
'n-us-ak': 'Alaska',
'n-us-al': 'Alabama',
'n-us-ar': 'Arkansas',
'n-us-az': 'Arizona',
'n-us-ca': 'California',
'n-us-co': 'Colorado',
'n-us-ct': 'Connecticut',
'n-us-dc': 'Washington (D.C.)',
'n-us-de': 'Delaware',
'n-us-fl': 'Florida',
'n-us-ga': 'Georgia',
'n-us-hi': 'Hawaii',
'n-us-ia': 'Iowa',
'n-us-id': 'Idaho',
'n-us-il': 'Illinois',
'n-us-in': 'Indiana',
'n-us-ks': 'Kansas',
'n-us-ky': 'Kentucky',
'n-us-la': 'Louisiana',
'n-us-ma': 'Massachusetts',
'n-us-md': 'Maryland',
'n-us-me': 'Maine',
'n-us-mi': 'Michigan',
'n-us-mn': 'Minnesota',
'n-us-mo': 'Missouri',
'n-us-ms': 'Mississippi',
'n-us-mt': 'Montana',
'n-us-nb': 'Nebraska',
'n-us-nc': 'North Carolina',
'n-us-nd': 'North Dakota',
'n-us-nh': 'New Hampshire',
'n-us-nj': 'New Jersey',
'n-us-nm': 'New Mexico',
'n-us-nv': 'Nevada',
'n-us-ny': 'New York',
'n-us-oh': 'Ohio',
'n-us-ok': 'Oklahoma',
'n-us-or': 'Oregon',
'n-us-pa': 'Pennsylvania',
'n-us-ri': 'Rhode Island',
'n-us-sc': 'south Carolina',
'n-us-sd': 'south Dakota',
'n-us-tn': 'Tennessee',
'n-us-tx': 'Texas',
'n-us-ut': 'Utah',
'n-us-va': 'Virginia',
'n-us-vt': 'Vermont',
'n-us-wa': 'Washington (State)',
'n-us-wi': 'Wisconsin',
'n-us-wv': 'West Virginia',
'n-us-wy': 'Wyoming',
'n-usa': 'Appalachian Mountains',
'n-usc': 'Middle West',
'n-use': 'Northeastern States',
'n-usl': 'Middle Atlantic States',
'n-usm': 'Mississippi River',
'n-usn': 'New England',
'n-uso': 'Ohio River',
'n-usp': 'West (U.S.)',
'n-usr': 'East (U.S.)',
'n-uss': 'Missouri River',
'n-ust': 'southwest, New',
'n-usu': 'southern States',
'n-usw': 'Northwest (U.S.)',
'n-xl': 'saint Pierre and Miquelon',
'nc': 'Central America',
'ncbh': 'Belize',
'nccr': 'Costa Rica',
'nccz': 'Canal Zone',
'nces': 'El Salvador',
'ncgt': 'Guatemala',
'ncho': 'Honduras',
'ncnq': 'Nicaragua',
'ncpn': 'Panama',
'nl': 'Great Lakes (North America); Lake States',
'nm': 'Mexico, Gulf of',
'np': 'Great Plains',
'nr': 'Rocky Mountains',
'nw': 'West Indies',
'nwaq': 'Antigua and Barbuda',
'nwaw': 'Aruba',
'nwbb': 'Barbados',
'nwbc': 'Barbuda',
'nwbf': 'Bahamas',
'nwbn': 'Bonaire',
'nwcj': 'Cayman Islands',
'nwco': 'Curaçao',
'nwcu': 'Cuba',
'nwdq': 'Dominica',
'nwdr': 'Dominican Republic',
'nweu': 'sint Eustatius',
'nwga': 'Greater Antilles',
'nwgd': 'Grenada',
'nwgp': 'Guadeloupe',
'nwgs': 'Grenadines',
'nwhi': 'Hispaniola',
'nwht': 'Haiti',
'nwjm': 'Jamaica',
'nwla': 'Antilles, Lesser',
'nwli': 'Leeward Islands (West Indies)',
'nwmj': 'Montserrat',
'nwmq': 'Martinique',
'nwna': 'Netherlands Antilles',
'nwpr': 'Puerto Rico',
'nwsb': 'saint-Barthélemy',
'nwsc': 'saint-Barthélemy',
'nwsd': 'saba',
'nwsn': 'sint Maarten',
'nwst': 'saint-Martin',
'nwsv': 'swan Islands (Honduras)',
'nwtc': 'Turks and Caicos Islands',
'nwtr': 'Trinidad and Tobago',
'nwuc': 'United States Miscellaneous Caribbean Islands',
'nwvb': 'British Virgin Islands',
'nwvi': 'Virgin Islands of the United States',
'nwvr': 'Virgin Islands',
'nwwi': 'Windward Islands (West Indies)',
'nwxa': 'Anguilla',
'nwxi': 'saint Kitts and Nevis',
'nwxk': 'saint Lucia',
'nwxm': 'saint Vincent and the Grenadines',
'p': 'Pacific Ocean',
'pn': 'North Pacific Ocean',
'po': 'Oceania',
'poas': 'American Samoa',
'pobp': 'solomon Islands',
'poci': 'Caroline Islands',
'pocp': 'Canton and Enderbury Islands',
'pocw': 'Cook Islands',
'poea': 'Easter Island',
'pofj': 'Fiji',
'pofp': 'French Polynesia',
'pogg': 'Galapagos Islands',
'pogn': 'Gilbert and Ellice Islands',
'pogu': 'Guam',
'poji': 'Johnston Island',
'pokb': 'Kiribati',
'poki': 'Kermadec Islands',
'poln': 'Line Islands',
'pome': 'Melanesia',
'pomi': 'Micronesia (Federated States)',
'ponl': 'New Caledonia',
'ponn': 'Vanuatu',
'ponu': 'Nauru',
'popc': 'Pitcairn Island',
'popl': 'Palau',
'pops': 'Polynesia',
'pory': 'Ryukyu Islands, Southern',
'posc': 'santa Cruz Islands',
'posh': 'samoan Islands',
'posn': 'solomon Islands',
'potl': 'Tokelau',
'poto': 'Tonga',
'pott': 'Micronesia',
'potv': 'Tuvalu',
'poup': 'United States Miscellaneous Pacific Islands',
'powf': 'Wallis and Futuna Islands',
'powk': 'Wake Island',
'pows': 'samoa',
'poxd': 'Mariana Islands',
'poxe': 'Marshall Islands',
'poxf': 'Midway Islands',
'poxh': 'Niue',
'ps': 'south Pacific Ocean',
'q': 'Cold regions',
'r': 'Arctic Ocean; Arctic regions',
's': 'south America',
's-ag': 'Argentina',
's-bl': 'Brazil',
's-bo': 'Bolivia',
's-ck': 'Colombia',
's-cl': 'Chile',
's-ec': 'Ecuador',
's-fg': 'French Guiana',
's-gy': 'Guyana',
's-pe': 'Peru',
's-py': 'Paraguay',
's-sr': 'suriname',
's-uy': 'Uruguay',
's-ve': 'Venezuela',
'sa': 'Amazon River',
'sn': 'Andes',
'sp': 'Rio de la Plata (Argentina and Uruguay)',
't': 'Antarctic Ocean; Antarctica',
't-ay': 'Antarctica',
'u': 'Australasia',
'u-ac': 'Ashmore and Cartier Islands',
'u-at': 'Australia',
'u-at-ac': 'Australian Capital Territory',
'u-atc': 'Central Australia',
'u-ate': 'Eastern Australia',
'u-atn': 'Northern Australia',
'u-at-ne': 'New South Wales',
'u-at-no': 'Northern Territory',
'u-at-qn': 'Queensland',
'u-at-sa': 'south Australia',
'u-at-tm': 'Tasmania',
'u-at-vi': 'Victoria',
'u-at-we': 'Western Australia',
'u-cs': 'Coral Sea Islands',
'u-nz': 'New Zealand',
'v': 'Communist countries',
'w': 'Tropics',
'x': 'Earth',
'xa': 'Eastern Hemisphere',
'xb': 'Northern Hemisphere',
'xc': 'southern Hemisphere',
'xd': 'Western Hemisphere',
'zd': 'Deep space',
'zju': 'Jupiter',
'zma': 'Mars',
'zme': 'Mercury',
'zmo': 'Moon',
'zne': 'Neptune',
'zo': 'Outer space',
'zpl': 'Pluto',
'zs': 'solar system',
'zsa': 'saturn',
'zsu': 'sun',
'zur': 'Uranus',
'zve': 'Venus',
},
'iso639-2b': # MARC_LANGUAGE_CODE_DICT
{
'aar': 'Afar',
'abk': 'Abkhaz',
'ace': 'Achinese',
'ach': 'Acoli',
'ada': 'Adangme',
'ady': 'Adygei',
'afa': 'Afroasiatic (Other)',
'afh': 'Afrihili (Artificial language)',
'afr': 'Afrikaans',
'ain': 'Ainu',
'ajm': 'Aljamía',
'aka': 'Akan',
'akk': 'Akkadian',
'alb': 'Albanian',
'ale': 'Aleut',
'alg': 'Algonquian (Other)',
'alt': 'Altai',
'amh': 'Amharic',
'ang': 'English, Old (ca. 450-1100)',
'anp': 'Angika',
'apa': 'Apache languages',
'ara': 'Arabic',
'arc': 'Aramaic',
'arg': 'Aragonese',
'arm': 'Armenian',
'arn': 'Mapuche',
'arp': 'Arapaho',
'art': 'Artificial (Other)',
'arw': 'Arawak',
'asm': 'Assamese',
'ast': 'Bable',
'ath': 'Athapascan (Other)',
'aus': 'Australian languages',
'ava': 'Avaric',
'ave': 'Avestan',
'awa': 'Awadhi',
'aym': 'Aymara',
'aze': 'Azerbaijani',
'bad': 'Banda languages',
'bai': 'Bamileke languages',
'bak': 'Bashkir',
'bal': 'Baluchi',
'bam': 'Bambara',
'ban': 'Balinese',
'baq': 'Basque',
'bas': 'Basa',
'bat': 'Baltic (Other)',
'bej': 'Beja',
'bel': 'Belarusian',
'bem': 'Bemba',
'ben': 'Bengali',
'ber': 'Berber (Other)',
'bho': 'Bhojpuri',
'bih': 'Bihari (Other)',
'bik': 'Bikol',
'bin': 'Edo',
'bis': 'Bislama',
'bla': 'siksika',
'bnt': 'Bantu (Other)',
'bos': 'Bosnian',
'bra': 'Braj',
'bre': 'Breton',
'btk': 'Batak',
'bua': 'Buriat',
'bug': 'Bugis',
'bul': 'Bulgarian',
'bur': 'Burmese',
'byn': 'Bilin',
'cad': 'Caddo',
'cai': 'Central American Indian (Other)',
'cam': 'Khmer',
'car': 'Carib',
'cat': 'Catalan',
'cau': 'Caucasian (Other)',
'ceb': 'Cebuano',
'cel': 'Celtic (Other)',
'cha': 'Chamorro',
'chb': 'Chibcha',
'che': 'Chechen',
'chg': 'Chagatai',
'chi': 'Chinese',
'chk': 'Chuukese',
'chm': 'Mari',
'chn': 'Chinook jargon',
'cho': 'Choctaw',
'chp': 'Chipewyan',
'chr': 'Cherokee',
'chu': 'Church Slavic',
'chv': 'Chuvash',
'chy': 'Cheyenne',
'cmc': 'Chamic languages',
'cnr': 'Montenegrin',
'cop': 'Coptic',
'cor': 'Cornish',
'cos': 'Corsican',
'cpe': 'Creoles and Pidgins, English-based (Other)',
'cpf': 'Creoles and Pidgins, French-based (Other)',
'cpp': 'Creoles and Pidgins, Portuguese-based (Other)',
'cre': 'Cree',
'crh': 'Crimean Tatar',
'crp': 'Creoles and Pidgins (Other)',
'csb': 'Kashubian',
'cus': 'Cushitic (Other)',
'cze': 'Czech',
'dak': 'Dakota',
'dan': 'Danish',
'dar': 'Dargwa',
'day': 'Dayak',
'del': 'Delaware',
'den': 'slavey',
'dgr': 'Dogrib',
'din': 'Dinka',
'div': 'Divehi',
'doi': 'Dogri',
'dra': 'Dravidian (Other)',
'dsb': 'Lower Sorbian',
'dua': 'Duala',
'dum': 'Dutch, Middle (ca. 1050-1350)',
'dut': 'Dutch',
'dyu': 'Dyula',
'dzo': 'Dzongkha',
'efi': 'Efik',
'egy': 'Egyptian',
'eka': 'Ekajuk',
'elx': 'Elamite',
'eng': 'English',
'enm': 'English, Middle (1100-1500)',
'epo': 'Esperanto',
'esk': 'Eskimo languages',
'esp': 'Esperanto',
'est': 'Estonian',
'eth': 'Ethiopic',
'ewe': 'Ewe',
'ewo': 'Ewondo',
'fan': 'Fang',
'fao': 'Faroese',
'far': 'Faroese',
'fat': 'Fanti',
'fij': 'Fijian',
'fil': 'Filipino',
'fin': 'Finnish',
'fiu': 'Finno-Ugrian (Other)',
'fon': 'Fon',
'fre': 'French',
'fri': 'Frisian',
'frm': 'French, Middle (ca. 1300-1600)',
'fro': 'French, Old (ca. 842-1300)',
'frr': 'North Frisian',
'frs': 'East Frisian',
'fry': 'Frisian',
'ful': 'Fula',
'fur': 'Friulian',
'gaa': 'Gã',
'gae': 'scottish Gaelix',
'gag': 'Galician',
'gal': 'Oromo',
'gay': 'Gayo',
'gba': 'Gbaya',
'gem': 'Germanic (Other)',
'geo': 'Georgian',
'ger': 'German',
'gez': 'Ethiopic',
'gil': 'Gilbertese',
'gla': 'scottish Gaelic',
'gle': 'Irish',
'glg': 'Galician',
'glv': 'Manx',
'gmh': 'German, Middle High (ca. 1050-1500)',
'goh': 'German, Old High (ca. 750-1050)',
'gon': 'Gondi',
'gor': 'Gorontalo',
'got': 'Gothic',
'grb': 'Grebo',
'grc': 'Greek, Ancient (to 1453)',
'gre': 'Greek, Modern (1453-)',
'grn': 'Guarani',
'gsw': 'swiss German',
'gua': 'Guarani',
'guj': 'Gujarati',
'gwi': 'Gwich\'in',
'hai': 'Haida',
'hat': 'Haitian French Creole',
'hau': 'Hausa',
'haw': 'Hawaiian',
'heb': 'Hebrew',
'her': 'Herero',
'hil': 'Hiligaynon',
'him': 'Western Pahari languages',
'hin': 'Hindi',
'hit': 'Hittite',
'hmn': 'Hmong',
'hmo': 'Hiri Motu',
'hrv': 'Croatian',
'hsb': 'Upper Sorbian',
'hun': 'Hungarian',
'hup': 'Hupa',
'iba': 'Iban',
'ibo': 'Igbo',
'ice': 'Icelandic',
'ido': 'Ido',
'iii': 'sichuan Yi',
'ijo': 'Ijo',
'iku': 'Inuktitut',
'ile': 'Interlingue',
'ilo': 'Iloko',
'ina': 'Interlingua (International Auxiliary Language Association)',
'inc': 'Indic (Other)',
'ind': 'Indonesian',
'ine': 'Indo-European (Other)',
'inh': 'Ingush',
'int': 'Interlingua (International Auxiliary Language Association)',
'ipk': 'Inupiaq',
'ira': 'Iranian (Other)',
'iri': 'Irish',
'iro': 'Iroquoian (Other)',
'ita': 'Italian',
'jav': 'Javanese',
'jbo': 'Lojban (Artificial language)',
'jpn': 'Japanese',
'jpr': 'Judeo-Persian',
'jrb': 'Judeo-Arabic',
'kaa': 'Kara-Kalpak',
'kab': 'Kabyle',
'kac': 'Kachin',
'kal': 'Kalâtdlisut',
'kam': 'Kamba',
'kan': 'Kannada',
'kar': 'Karen languages',
'kas': 'Kashmiri',
'kau': 'Kanuri',
'kaw': 'Kawi',
'kaz': 'Kazakh',
'kbd': 'Kabardian',
'kha': 'Khasi',
'khi': 'Khoisan (Other)',
'khm': 'Khmer',
'kho': 'Khotanese',
'kik': 'Kikuyu',
'kin': 'Kinyarwanda',
'kir': 'Kyrgyz',
'kmb': 'Kimbundu',
'kok': 'Konkani',
'kom': 'Komi',
'kon': 'Kongo',
'kor': 'Korean',
'kos': 'Kosraean',
'kpe': 'Kpelle',
'krc': 'Karachay-Balkar',
'krl': 'Karelian',
'kro': 'Kru (Other)',
'kru': 'Kurukh',
'kua': 'Kuanyama',
'kum': 'Kumyk',
'kur': 'Kurdish',
'kus': 'Kusaie',
'kut': 'Kootenai',
'lad': 'Ladino',
'lah': 'Lahndā',
'lam': 'Lamba (Zambia and Congo)',
'lan': 'Occitan (post 1500)',
'lao': 'Lao',
'lap': 'sami',
'lat': 'Latin',
'lav': 'Latvian',
'lez': 'Lezgian',
'lim': 'Limburgish',
'lin': 'Lingala',
'lit': 'Lithuanian',
'lol': 'Mongo-Nkundu',
'loz': 'Lozi',
'ltz': 'Luxembourgish',
'lua': 'Luba-Lulua',
'lub': 'Luba-Katanga',
'lug': 'Ganda',
'lui': 'Luiseño',
'lun': 'Lunda',
'luo': 'Luo (Kenya and Tanzania)',
'lus': 'Lushai',
'mac': 'Macedonian',
'mad': 'Madurese',
'mag': 'Magahi',
'mah': 'Marshallese',
'mai': 'Maithili',
'mak': 'Makasar',
'mal': 'Malayalam',
'man': 'Mandingo',
'mao': 'Maori',
'map': 'Austronesian (Other)',
'mar': 'Marathi',
'mas': 'Maasai',
'max': 'Manx',
'may': 'Malay',
'mdf': 'Moksha',
'mdr': 'Mandar',
'men': 'Mende',
'mga': 'Irish, Middle (ca. 1100-1550)',
'mic': 'Micmac',
'min': 'Minangkabau',
'mis': 'Miscellaneous languages',
'mkh': 'Mon-Khmer (Other)',
'mla': 'Malagasy',
'mlg': 'Malagasy',
'mlt': 'Maltese',
'mnc': 'Manchu',
'mni': 'Manipuri',
'mno': 'Manobo languages',
'moh': 'Mohawk',
'mol': 'Moldavian',
'mon': 'Mongolian',
'mos': 'Mooré',
'mul': 'Multiple languages',
'mun': 'Munda (Other)',
'mus': 'Creek',
'mwl': 'Mirandese',
'mwr': 'Marwari',
'myn': 'Mayan languages',
'myv': 'Erzya',
'nah': 'Nahuatl',
'nai': 'North American Indian (Other)',
'nap': 'Neapolitan Italian',
'nau': 'Nauru',
'nav': 'Navajo',
'nbl': 'Ndebele (South Africa)',
'nde': 'Ndebele (Zimbabwe)',
'ndo': 'Ndonga',
'nds': 'Low German',
'nep': 'Nepali',
'new': 'Newari',
'nia': 'Nias',
'nic': 'Niger-Kordofanian (Other)',
'niu': 'Niuean',
'nno': 'Norwegian (Nynorsk)',
'nob': 'Norwegian (Bokmål)',
'nog': 'Nogai',
'non': 'Old Norse',
'nor': 'Norwegian',
'nqo': 'N\'Ko',
'nso': 'Northern Sotho',
'nub': 'Nubian languages',
'nwc': 'Newari, Old',
'nya': 'Nyanja',
'nym': 'Nyamwezi',
'nyn': 'Nyankole',
'nyo': 'Nyoro',
'nzi': 'Nzima',
'oci': 'Occitan (post-1500)',
'oji': 'Ojibwa',
'ori': 'Oriya',
'orm': 'Oromo',
'osa': 'Osage',
'oss': 'Ossetic',
'ota': 'Turkish, Ottoman',
'oto': 'Otomian languages',
'paa': 'Papuan (Other)',
'pag': 'Pangasinan',
'pal': 'Pahlavi',
'pam': 'Pampanga',
'pan': 'Panjabi',
'pap': 'Papiamento',
'pau': 'Palauan',
'peo': 'Old Persian (ca. 600-400 B.C.)',
'per': 'Persian',
'phi': 'Philippine (Other)',
'phn': 'Phoenician',
'pli': 'Pali',
'pol': 'Polish',
'pon': 'Pohnpeian',
'por': 'Portuguese',
'pra': 'Prakrit languages',
'pro': 'Provençal (to 1500)',
'pus': 'Pushto',
'que': 'Quechua',
'raj': 'Rajasthani',
'rap': 'Rapanui',
'rar': 'Rarotongan',
'roa': 'Romance (Other)',
'roh': 'Raeto-Romance',
'rom': 'Romani',
'rum': 'Romanian',
'run': 'Rundi',
'rup': 'Aromanian',
'rus': 'Russian',
'sad': 'sandawe',
'sag': 'sango (Ubangi Creole)',
'sah': 'Yakut',
'sai': 'south American Indian (Other)',
'sal': 'salishan languages',
'sam': 'samaritan Aramaic',
'san': 'sanskrit',
'sao': 'samoan',
'sas': 'sasak',
'sat': 'santali',
'scc': 'serbian',
'scn': 'sicilian Italian',
'sco': 'scots',
'scr': 'Croatian',
'sel': 'selkup',
'sem': 'semitic (Other)',
'sga': 'Irish, Old (to 1100)',
'sgn': 'sign languages',
'shn': 'shan',
'sho': 'shona',
'sid': 'sidamo',
'sin': 'sinhalese',
'sio': 'siouan (Other)',
'sit': 'sino-Tibetan (Other)',
'sla': 'slavic (Other)',
'slo': 'slovak',
'slv': 'slovenian',
'sma': 'southern Sami',
'sme': 'Northern Sami',
'smi': 'sami',
'smj': 'Lule Sami',
'smn': 'Inari Sami',
'smo': 'samoan',
'sms': 'skolt Sami',
'sna': 'shona',
'snd': 'sindhi',
'snh': 'sinhalese',
'snk': 'soninke',
'sog': 'sogdian',
'som': 'somali',
'son': 'songhai',
'sot': 'sotho',
'spa': 'spanish',
'srd': 'sardinian',
'srn': 'sranan',
'srp': 'serbian',
'srr': 'serer',
'ssa': 'Nilo-Saharan (Other)',
'sso': 'sotho',
'ssw': 'swazi',
'suk': 'sukuma',
'sun': 'sundanese',
'sus': 'susu',
'sux': 'sumerian',
'swa': 'swahili',
'swe': 'swedish',
'swz': 'swazi',
'syc': 'syriac',
'syr': 'syriac, Modern',
'tag': 'Tagalog',
'tah': 'Tahitian',
'tai': 'Tai (Other)',
'taj': 'Tajik',
'tam': 'Tamil',
'tar': 'Tatar',
'tat': 'Tatar',
'tel': 'Telugu',
'tem': 'Temne',
'ter': 'Terena',
'tet': 'Tetum',
'tgk': 'Tajik',
'tgl': 'Tagalog',
'tha': 'Thai',
'tib': 'Tibetan',
'tig': 'Tigré',
'tir': 'Tigrinya',
'tiv': 'Tiv',
'tkl': 'Tokelauan',
'tlh': 'Klingon (Artificial language)',
'tli': 'Tlingit',
'tmh': 'Tamashek',
'tog': 'Tonga (Nyasa)',
'ton': 'Tongan',
'tpi': 'Tok Pisin',
'tru': 'Truk',
'tsi': 'Tsimshian',
'tsn': 'Tswana',
'tso': 'Tsonga',
'tsw': 'Tswana',
'tuk': 'Turkmen',
'tum': 'Tumbuka',
'tup': 'Tupi languages',
'tur': 'Turkish',
'tut': 'Altaic (Other)',
'tvl': 'Tuvaluan',
'twi': 'Twi',
'tyv': 'Tuvinian',
'udm': 'Udmurt',
'uga': 'Ugaritic',
'uig': 'Uighur',
'ukr': 'Ukrainian',
'umb': 'Umbundu',
'und': 'Undetermined',
'urd': 'Urdu',
'uzb': 'Uzbek',
'vai': 'Vai',
'ven': 'Venda',
'vie': 'Vietnamese',
'vol': 'Volapük',
'vot': 'Votic',
'wak': 'Wakashan languages',
'wal': 'Wolayta',
'war': 'Waray',
'was': 'Washoe',
'wel': 'Welsh',
'wen': 'sorbian (Other)',
'wln': 'Walloon',
'wol': 'Wolof',
'xal': 'Oirat',
'xho': 'Xhosa',
'yao': 'Yao (Africa)',
'yap': 'Yapese',
'yid': 'Yiddish',
'yor': 'Yoruba',
'ypk': 'Yupik languages',
'zap': 'Zapotec',
'zbl': 'Blissymbolics',
'zen': 'Zenaga',
'zha': 'Zhuang',
'znd': 'Zande languages',
'zul': 'Zulu',
'zun': 'Zuni',
'zxx': 'No linguistic content',
'zza': 'Zaza',
},
'coll_pid_correction':
{
'ult_collec': 'default_collection',
'sl': ''
},
'coll_pid': # Persistent Identifier for collections in Islandora
{
'collection.120_review': '19th Century Schoolbooks (Review)',
'collection.120': '19th Century Schoolbooks',
'collection.121': 'Abner Shimony Papers',
'collection.168': 'Adolph M. Foerster Collection',
'collection.33': 'Aerial Photographs of Pittsburgh',
'collection.164': 'African American Chamber of Commerce of Western Pennsylvania',
'collection.212': 'African American Jazz Preservation Society of Pittsburgh Oral History Project Records and Recordings',
'collection.176': 'African American Construction Workers of Pittsburgh Photographs',
'collection.378': 'Alberto Britos Scrapbook on Nicolás Guillén Visit to Uruguay [Álbum de recortes de Alberto Britos sobre la visita de Nicolás Guillén a Uruguay]',
'collection.15_review': 'Alexander Addison Papers (Review)',
'collection.15': 'Alexander Addison Papers',
'collection.249': 'Alexander Cumming Papers',
'collection.249_review': 'Alexander Cumming Papers (Review)',
'collection.13': 'Alexander Lowy Papers',
'collection.278': 'Alfred P. James Papers',
'collection.34': 'Allegheny Conference on Community Development Photographs',
'collection.320': 'Allegheny County Photography Department Photographs',
'collection.320_review': 'Allegheny County Photography Department Photographs (Review)',
'collection.105': 'Allegheny County Recorder of Deed Manumission and Indenture Records',
'collection.180_review': 'Allegheny County Courthouse and Jail Architectural Records (Review)',
'collection.180': 'Allegheny County Courthouse and Jail Architectural Records',
'collection.108_review': 'Allegheny Observatory Records (Review)',
'collection.108': 'Allegheny Observatory Records',
'collection.122': 'Allen Family Papers',
'collection.274': 'Aluminum Company of America Photographs',
'collection.107': 'American Left Ephemera Collection',
'collection.107_review': 'American Left Ephemera Collection (Review)',
'collection.372': 'American Music and Performing Arts Text Resources',
'collection.245_review': 'An Attempt to Describe the Future of the United States (Review)',
'collection.245': 'An Attempt to Describe the Future of the United States',
'collection.349': 'Andrew Carnegie Correspondence Collection',
'collection.229': 'Anthony Debons Papers',
'collection.235': 'Archives of Industrial Society Moving Images Collection',
'collection.226': 'Archives of Industrial Society Photograph Collection',
'collection.123': 'Archives of Scientific Philosophy',
'collection.123_review': 'Archives of Scientific Philosophy (Review)',
'collection.288': 'Arlen Specter Senatorial Papers',
'collection.288_review': 'Arlen Specter Senatorial Papers (Review)',
'collection.217': 'Arthur J. Benson Papers',
'collection.263_review': 'Asa Fletcher Ledger (Review)',
'collection.263': 'Asa Fletcher Ledger',
'islandora:audio_collection': 'Audio Collection',
'collection.1': 'Audubon\'s Birds of America',
'collection.169_review': 'Autograph Files of H. Edmund Friesell (Review)',
'collection.169': 'Autograph Files of H. Edmund Friesell',
'collection.bgilling': 'BGILLING TESTING',
'collection.124': 'Barry Rosensteel Japanese Print Collection',
'islandora:sp_basic_image_collection': 'Basic Image Collection',
'collection.246_review': 'Beazel Family Papers (Review)',
'collection.246': 'Beazel Family Papers',
'collection.16': 'Bedford County Township Tax Receipts',
'collection.328': 'Bill Green Photographs',
'collection.187_review': 'Birmingham United Church of Christ Records (Review)',
'collection.187': 'Birmingham United Church of Christ Records',
'collection.209': 'Black Sport in Pittsburgh Records of Oral History Collection',
'collection.308': 'Blind and Vision Rehabilitation Services of Pittsburgh',
'collection.341': 'Bob Nelkin Collection of ACC-PARC Records',
'islandora:bookCollection': 'Book Collection',
'books:collection': 'Book Collection',
'collection.304': 'Branton H. Henderson Papers',
'collection.304_review': 'Branton H. Henderson Papers (Review)',
'collection.309_review': 'Breathe Pennsylvania Records (Review)',
'collection.309': 'Breathe Pennsylvania Records',
'collection.bdgregg': 'Brian Gregg\'s Testing Collection',
'collection.35': 'Bruce Drisbach-American Steel & Wire Company Photographs',
'collection.125': 'Bruno De Finetti Papers',
'collection.285': 'Bryce Brothers and Lenox Incorporated Glass Records',
'collection.115_review': 'Burd-Shippen Family Papers (Review)',
'collection.115': 'Burd-Shippen Family Papers',
'collection.186': 'Bureau of Building Inspection, Department of Public Safety, Pittsburgh, Pa. Records',
'collection.186_review': 'Bureau of Building Inspection, Department of Public Safety, Pittsburgh, Pa. Records (Review)',
'collection.32': 'CONSOL Energy, Inc. Mine Maps and Records',
'collection.32_review': 'CONSOL Energy, Inc. Mine Maps and Records (Review)',
'collection.311': 'Camp Johnson Photographs',
'collection.126_review': 'Carl Gustav Hempel Papers (Review)',
'collection.126': 'Carl Gustav Hempel Papers',
'collection.380': 'Carl T. Schofer Diaries',
'collection.199': 'Carl Truman Johnston Photographs',
'collection.363': 'Carnegie Library of Pittsburgh 125th Anniversary Collection',
'collection.36': 'Carnegie Museum of Art Collection of Photographs',
'collection.151': 'Carnegie Museum of Natural History Archives',
'collection.214': 'Carolyn S. Schumacher Papers',
'collection.279_review': 'Charles Bonaventure Scully Journal (Review)',
'collection.279': 'Charles Bonaventure Scully Journal',
'collection.193_review': 'Charles C. McGovern Papers (Review)',
'collection.193': 'Charles C. McGovern Papers',
'collection.383': 'Charles Henry Pace and Frankie W. Pace Gospel Music Collection',
'collection.37': 'Charles M. Stotz Photographs',
'collection.377': 'Charles N. Boyd Collection',
'collection.207': 'Charles Owen Rice Papers',
'collection.38': 'Charles R. Martin Photographs',
'collection.157': 'Charles Richardson Photographs',
'collection.127': 'Chartres: Cathedral of Notre-Dame',
'collection.236': 'Chatham University Chronological Photograph Files',
'collection.239': 'Chatham University May Day Collection',
'collection.237': 'Chatham University Shadyside Campus Lantern Slide Collection',
'collection.344': 'Children\'s Aid Society of Western Pennsylvania Records',
'collection.337': 'Children\'s Service Bureau Records',
'collection.302': 'China\'s Cultural Revolution in Memories: The CR/10 Project',
'collection.179_review': 'Chinese Land Records (Review)',
'collection.179': 'Chinese Land Records',
'collection.196_review': 'Chinese Marriage Documents (Review)',
'collection.196': 'Chinese Marriage Documents',
'collection.244': 'Chinese Overseas Student Newsletters',
'collection.251': 'Chinese Political Prisoner Photograph Collection',
'collection.251_review': 'Chinese Political Prisoner Photograph Collection (Review)',
'collection.101': 'Christopher Gist\'s Journals by William M. Darlington',
'collection.294': 'City of Pittsburgh Geodetic and Topographic Survey Maps',
'root': 'Collections (Root)',
'collection.106': 'Communist Collection of A.E. Forbes',
'islandora:compound_collection': 'Compound Collection',
'collection.144': 'Conference between the Six Nations and the Quakers Minutes',
'collection.154': 'Congregation B\'nai Israel Photographs',
'collection.269': 'Constitutional Convention of the State of New York Copybook',
'collection.269_review': 'Constitutional Convention of the State of New York Copybook (Review)',
'collection.174': 'Coroner\'s Office Records, Allegheny County, Pa.',
'collection.174_review': 'Coroner\'s Office Records, Allegheny County, Pa. (Review)',
'collection.353': 'Crafton Public Library Collection',
'collection.314': 'D. L. Clark Company Papers and Photographs',
'collection.18': 'Daniel Brodhead Papers',
'collection.145_review': 'Darlington Autograph Files (Review)',
'collection.145': 'Darlington Autograph Files',
'collection.153': 'Darlington Digital Library',
'collection.153_review': 'Darlington Digital Library (Review)',
'collection.100_review': 'Darlington Family Papers (Review)',
'collection.100': 'Darlington Family Papers',
'collection.173': 'Daughters of Erin Court #9 Records',
'collection.173_review': 'Daughters of Erin Court #9 Records (Review)',
'islandora:default_collection': 'Default Parent Collection namespace "islandora"',
'default_collection': 'Default Parent Collection namespace "pitt"',
'ult_collect': 'Default Parent Collection namespace "pitt"',
'collection.345': 'Department of Public Health Annual Reports, Pittsburgh, Pennsylvania',
'collection.368': 'Dialogues in Afrolatinidad',
'collection.143_review': 'Dick Thornburgh Papers (Review)',
'collection.143': 'Dick Thornburgh Papers',
'collection.301': 'Dime Store Novels',
'collection.301_review': 'Dime Store Novels (Review)',
'collection.49': 'Directories',
'documenting': 'Documenting Pitt Root Collection',
'collection.232': 'Donald M. Goldstein Papers',
'collection.102': 'Donohoe Family Papers',
'collection.40': 'Dorsey-Turfley Family Photographs',
'collection.327': 'Dr. Minglu Gao Lecture Series',
'collection.228': 'Dr. Thomas E. Starzl Papers',
'collection.19': 'Dunning McNair and Dunning Robert McNair Papers',
'collection.336': 'Dwight H. Roberts Collection',
'collection.41': 'Edward J. Shourek Photographs',
'collection.243': 'Eichleay Engineering Corporation Records and Photographs',
'collection.104': 'Eliphalet Smith Account Book',
'collection.182_review': 'Elsie H. Hillman Papers (Review)',
'collection.182': 'Elsie H. Hillman Papers',
'collection.306': 'Emerging Masters Collection, 1954-1989',
'collection.272_review': 'Enoch Wright Ledger (Review)',
'collection.272': 'Enoch Wright Ledger',
'collection.348': 'Environmental Action Newspaper',
'collection.20': 'Ephraim Douglass Ledgers',
'collection.340': 'Erroll Garner Archive',
'collection.31': 'Extension of the Pittsburgh City Limits Minute Book',
'collection.42': 'F. Theodore Wagner Papers',
'collection.53': 'Father Cox Papers',
'collection.190_review': 'Fidelis Zitterbart Manuscripts (Review)',
'collection.190': 'Fidelis Zitterbart Manuscripts',
'fa.documenting': 'Finding Aids',
'fa.digital': 'Finding Aids',
'collection.188_review': 'First Congregational Church, Etna, Pa. Records (Review)',
'collection.188': 'First Congregational Church, Etna, Pa. Records',
'collection.43': 'First Trinity Evangelical Lutheran Church, Pittsburgh, Pa. Records',
'collection.292': 'Flood Commission of Pittsburgh, Pennsylvania',
'collection.254_review': 'Ford E. and Harriet R. Curtis Theatre Collection of Pittsburgh Theatre Programs (Review)',
'collection.254': 'Ford E. and Harriet R. Curtis Theatre Collection of Pittsburgh Theatre Programs',
'collection.198': 'Forrest "Bud" Harris Photographs',
'collection.360': 'Fox Chapel Garden Club Records',
'collection.367': 'Frances Hesselbein Papers',
'collection.266': 'Francis Newton Thorpe\'s Typescript Manuscript of A History of the American People',
'collection.266_review': 'Francis Newton Thorpe\'s Typescript Manuscript of A History of the American People (Review)',
'collection.44': 'Frank B. Fairbanks Rail Transportation Archive',
'collection.366': 'Frank E. Bolden Papers',
'collection.128': 'Frank Plumpton Ramsey Papers',
'collection.128_review': 'Frank Plumpton Ramsey Papers (Review)',
'collection.300_review': 'Franklin Literary Society Minutes (Review)',
'collection.300': 'Franklin Literary Society Minutes',
'collection.112': 'Fred Wright Cartoons',
'collection.112_review': 'Fred Wright Cartoons (Review)',
'collection.45': 'Frederick T. Gretton Photographs',
'collection.178': 'Frederick J. Osterling Collection',
'collection.46': 'Fuchs Family Papers and Photographs',
'collection.258_review': 'Fur Trader\'s Journal (Review)',
'collection.258': 'Fur Trader\'s Journal',
'collection.220': 'G. Norman Reis Papers',
'collection.240': 'G.M. Hopkins Company Maps',
'collection.165': 'George H. Love Interviews',
'collection.183_review': 'George Washington Collection (Review)',
'collection.183': 'George Washington Collection',
'collection.286': 'George Westinghouse Museum Collection',
'collection.17': 'Greenstone United Methodist Church, Avalon, Pa. Records',
'collection.290': 'Gulf Oil Corporation Records',
'collection.161': 'H.H. Seiferth Sign Company Photographs',
'collection.47': 'H.J. Heinz Company Photographs',
'collection.247': 'H.K. Porter Co., Pittsburgh, Pa. Records',
'collection.177_review': 'Hans Reichenbach Papers (Review)',
'collection.177': 'Hans Reichenbach Papers',
'collection.146': 'Harold Corsini Photographs',
'collection.312': 'Harold V. Cohen Photographs',
'collection.356': 'Harper Family Papers',
'collection.48': 'Hebrew Institute Photographs',
'fa.heinz': 'Heinz History Center Finding Aids',
'collection.331': 'Heinz History Center, Italian American Program Oral Histories',
'collection.156': 'Henry Clay Frick Business Records',
'collection.156_review': 'Henry Clay Frick Business Records (Review)',
'collection.335': 'Henry F. and Kate B. Hebley Collection of Soviet Lantern Slides',
'collection.103': 'Henry Marie Brackenridge and Family Papers',
'collection.208': 'Henry Sterling Papers',
'collection.208_review': 'Henry Sterling Papers (Review)',
'collection.384': 'Herb Ferguson Photographs',
'collection.129_review': 'Hervey Allen Papers (Review)',
'collection.129': 'Hervey Allen Papers',
'collection.241': 'Historic Pittsburgh Book Collection',
'collection.241_review': 'Historic Pittsburgh Book Collection (Review)',
'collection.49_review': 'Historic Pittsburgh City Directories (Review)',
'histpitt': 'Historic Pittsburgh Root Collection',
'collection.50': 'Historical Society of Upper St. Clair Collection',
'collection.352': 'Homer S. Brown Papers',
'collection.268_review': 'Horn Papers (Review)',
'collection.268': 'Horn Papers',
'collection.175': 'Hotel Schenley Register',
'collection.310': 'Howard Etzel Photograph Collection',
'collection.21': 'Hugh Henry Brackenridge and Andrew Watson Papers',
'collection.277_review': 'Indian Depredation Claims (Review)',
'collection.277': 'Indian Depredation Claims',
'collection.364': 'Internal Use',
'collection.51': 'Irene Kaufmann Settlement Photographs',
'collection.172': 'Irish Centre of Pittsburgh Records',
'collection.172_review': 'Irish Centre of Pittsburgh Records (Review)',
'collection.114': 'Iroquois Land Deed',
'collection.369': 'Isaac Meason Ledger and Mount Vernon Furnace Records',
'collection.273': 'Isaac and Samuel Miller Farm Account Book',
'collection.273_review': 'Isaac and Samuel Miller Farm Account Book (Review)',
'collection.52': 'James Benney Photographs',
'collection.22': 'James Veech Copybook of the General William Irvine Papers',
'collection.116': 'James Wilkinson Papers',
'collection.116_review': 'James Wilkinson Papers (Review)',
'collection.343': 'Jennie Bradley Roessing Papers',
'collection.54': 'Jewish Sports Hall of Fame of Western Pennsylvania Photographs',
'collection.305_review': 'Joel B. Levinson Photographs (Review)',
'collection.305': 'Joel B. Levinson Photographs',
'collection.55': 'John Gates Photographs',
'collection.347': 'John Lorkovich Undertakers Record Book',
'collection.203': 'John M. Tate, Jr. Collection of Notes, Pictures and Documents relating to the Harmony Society',
'collection.271': 'John Miller Day Book',
'collection.271_review': 'John Miller Day Book (Review)',
'collection.213': 'John P. Hoerr Oral History Collection',
'collection.280': 'John R. Bickley Diary',
'collection.280_review': 'John R. Bickley Diary (Review)',
'collection.184': 'John Woodruff Scrapbooks',
'collection.184_review': 'John Woodruff Scrapbooks (Review)',
'collection.23': 'Jonathan Forman Papers',
'collection.56': 'Jones & Laughlin Steel Corporation Photographs',
'collection.166': 'Joseph H. Larwill Manuscript Notebook',
'collection.276': 'Joseph St. Leger d\'Happart Papers',
'collection.379': 'Julio Elizalde Papers [Julio Elizalde Escritos]',
'collection.303_review': 'Juniata Crossings House Records (Review)',
'collection.303': 'Juniata Crossings House Records',
'collection.206': 'K. Leroy Irvis Papers',
'collection.318_review': 'Kaufmann\'s Department Store Photographs (Review)',
'collection.318': 'Kaufmann\'s Department Store Photographs',
'collection.614': 'Kayla\'s Test Collection',
'collection.57': 'Ken Kobus Collection',
'collection.362': 'Kennywood Park Records',
'collection.58': 'Kingsley Association Records',
'collection.130': 'Kōgyo: The Art of Noh',
'islandora:sp_large_image_collection': 'Large Image Collection',
'collection.267_review': 'Lieutenant Colonel Robert Stewart Letters (Review)',
'collection.267': 'Lieutenant Colonel Robert Stewart Letters',
'collection.223': 'Lillian A. Friedberg Postcards',
'collection.210': 'Local News Television in Pittsburgh: An Oral History Project Papers and Recordings',
'collection.333': 'Louis Semple Clarke Collection',
'collection.221': 'Lovelace Marionette Theatre Company Records',
'desmone-0001': 'Luke Desmone Oral History Interview',
'collection.59': 'Lyon, Shorb & Company Photographs',
'collection.281_review': 'M. Stanford Jackson Papers (Review)',
'collection.281': 'M. Stanford Jackson Papers',
'collection.265_review': 'Machine Shop Ledger (Review)',
'collection.265': 'Machine Shop Ledger',
'collection.242': 'Magee Family Papers',
'islandora:manuscriptCollection': 'Manuscript Collection',
'collection.98': 'March of the Pittsburgh Blues Copybook',
'collection.202': 'Marshall W. "Major" Taylor Scrapbooks',
'collection.275_review': 'Mary Elinor Lazenby Papers (Review)',
'collection.275': 'Mary Elinor Lazenby Papers',
'collection.185_review': 'Mary Roberts Rinehart Papers (Review)',
'collection.185': 'Mary Roberts Rinehart Papers',
'collection.197': 'Max A. Lauffer Papers',
'collection.322': 'McConway and Torely Company Records',
'collection.201': 'McFarland-Hall-Beck Families Papers',
'collection.287': 'Mellon Bank Records',
'collection.332': 'Melvin Seidenberg Photographs',
'collection.60': 'Mesta Machine Company Photographs',
'collection.222': 'Mildred Miller Posvar Papers',
'collection.264': 'Minute Book of the American Party of Westmorland County, Pennsylvania',
'collection.264_review': 'Minute Book of the American Party of Westmorland County, Pennsylvania (Review)',
'collection.370': 'Mirskey Collection',
'collection.131_review': 'Modern China Studies (Review)',
'collection.131': 'Modern China Studies',
'collection.24': 'Monongahela Navigation Company Copybook',
'collection.61': 'Monongahela Railway Company Photographs',
'collection.62': 'Monroeville Historical Society Collection',
'collection.86': 'Montefiore Hospital Photographs',
'collection.204': 'Mrs. Hanlin\'s Diary',
'collection.374': 'Music Performances in Pittsburgh',
'collection.227': 'Natalie L. M. Petesch Papers',
'collection.110_review': 'National Council of Jewish Women (NCJW), Pittsburgh Section, Records (Review)',
'collection.110': 'National Council of Jewish Women (NCJW), Pittsburgh Section, Records',
'collection.355': 'National Organization for Women (NOW) Newsletters',
'islandora:newspaper_collection': 'Newspaper Collection',
'collection.63': 'Northern Liberties Bridge Company Ledger',
'collection.64': 'Northland Historical Image Collection',
'collection.64_review': 'Northland Historical Image Collection (Review)',
'collection.39_review': 'Notes sur le Pays a l\'Ouest des Etats Unies d\' Amerique [The Navigator] (Review)',
'collection.39': 'Notes sur le Pays a l\'Ouest des Etats Unies d\' Amerique [The Navigator]',
'collection.65': 'Oakmont Historical Image Collection',
'collection.25': 'Ohio Company Papers',
'collection.66': 'Oliver M. Kaufmann Photograph Collection of the Irene Kaufmann Settlement',
'islandora:oralhistories_collection': 'Oral Histories Collection',
'collection.67': 'Otto\'s Suburban Dairy Photographs',
'islandora:sp_pdf_collection': 'PDF Collection',
'collection.291': 'PPG Industries Records',
'collection.163_review': 'Pamela J. Stewart & Andrew J. Strathern Archive (Review)',
'collection.163': 'Pamela J. Stewart & Andrew J. Strathern Archive',
'collection.354': 'Paris Exhibition of 1900: Le Lyon Repubilcain',
'collection.339': 'Patricia Clapp Papers ',
'collection.315': 'Paul Lawrence Peeler Papers and Photographs',
'collection.68': 'Paul Slantis Photographs',
'collection.69': 'Pennsylvania Railroad Photographs',
'collection.260': 'Persis Kingsley Token Album',
'collection.260_review': 'Persis Kingsley Token Album (Review)',
'collection.70': 'Pitcairn Historical Society Collection',
'collection.70_review': 'Pitcairn Historical Society Image Collection (Review)',
'collection.159': 'Pitt Administration',
'collection.159_review': 'Pitt Administration (Review)',
'collection.2_review': 'Pitt Alumni (Review)',
'collection.2': 'Pitt Alumni',
'collection.4': 'Pitt Athletics',
'collection.160': 'Pitt Campus Life',
'collection.160_review': 'Pitt Campus Life (Review)',
'collection.5': 'Pitt Faculty',
'collection.5_review': 'Pitt Faculty (Review)',
'collection.6': 'Pitt Nationality Rooms',
'collection.6_review': 'Pitt Nationality Rooms (Review)',
'collection.9': 'Pitt News',
'collection.7': 'Pitt Photographs',
'collection.7_review': 'Pitt Photographs (Review)',
'collection.11_review': 'Pitt Press Releases (Review)',
'collection.3_review': 'Pitt Publications (Review)',
'collection.3': 'Pitt Publications',
'collection.8_review': 'Pitt Student Life (Review)',
'collection.8': 'Pitt Student Life',
'collection.12_review': 'Pitt Yearbooks (Review)',
'collection.12': 'Pitt Yearbooks',
'collection.284_review': 'Pittsburg Daily Dispatch (Review)',
'collection.284': 'Pittsburg Daily Dispatch',
'collection.248_review': 'Pittsburg, Shawmut & Northern Railroad Company Records (Review)',
'collection.248': 'Pittsburg, Shawmut & Northern Railroad Company Records',
'collection.346': 'Pittsburgh Academy of Medicine Records',
'collection.297': 'Pittsburgh Bicentennial',
'collection.155': 'Pittsburgh Bureau of Building Inspection Photographs',
'collection.329': 'Pittsburgh Census Tract Maps and Data',
'collection.72': 'Pittsburgh City Photographer Collection',
'collection.72_review': 'Pittsburgh City Photographer Collection (Review)',
'collection.359': 'Pittsburgh International Lesbian and Gay Film Festival Records',
'collection.381': 'Pittsburgh Philanthropy Oral History Interviews',
'collection.317_review': 'Pittsburgh Photographic Library Collection (Review)',
'collection.317': 'Pittsburgh Photographic Library Collection',
'collection.73': 'Pittsburgh Prints from the Collection of Wesley Pickard',
'collection.358': 'Pittsburgh Public Administration Reports and Studies',
'collection.74': 'Pittsburgh Public Schools Photographs',
'collection.75': 'Pittsburgh Railways Company Records',
'collection.152': 'Pittsburgh Speech and Society Project',
'collection.150': 'Pittsburgh Symphony Orchestra Posters',
'collection.10': 'Pittsburgh Theatre',
'collection.99': 'Pittsburgh Waste Book and Fort Pitt Trading Post Papers',
'collection.71': 'Pittsburgh and Lake Erie Railroad Company Records',
'collection.71_review': 'Pittsburgh and Lake Erie Railroad Company Records (Review)',
'collection.76': 'Pittsburgh, Fort Wayne, and Chicago Railway Company Photographs',
'collection.77': 'Point Park University Archives',
'collection.351': 'Proceedings of the Allegheny County (Pa.) Office of the Coroner\'s Open Inquest into the death of Jonny Gammage',
'collection.78': 'Progress Photographs: William Penn Hotel',
'collection.238': 'Rachel Carson Collection',
'collection.250_review': 'Railroad Stock Certificate Collection (Review)',
'collection.250': 'Railroad Stock Certificate Collection',
'collection.219': 'Ralph G. Allen Burlesque Collection',
'collection.132_review': 'Ramón Gómez de la Serna Papers (Review)',
'collection.132': 'Ramón Gómez de la Serna Papers',
'collection.298_review': 'Rare Books and Imprints (Review)',
'collection.298': 'Rare Books and Imprints',
'collection.224_review': 'Reed Family Papers (Review)',
'collection.224': 'Reed Family Papers',
'collection.361': 'Reverend David J. Beale Collection',
'collection.133': 'Richard C. Jeffrey Papers',
'collection.87': 'Richard E. Rauh Photographs',
'collection.167': 'Ridgelawn Cemetery Company at German Evangelical Lutheran St. Peter\'s Cemetery, Pittsburgh, Pa. Records of Burials',
'collection.147': 'Robert G. Pflaum Photograph Collection',
'collection.119': 'Robert J. Walker Papers',
'collection.119_review': 'Robert J. Walker Papers (Review)',
'collection.26': 'Robert McKnight Diaries',
'collection.27': 'Robert Stobo Papers',
'collection.189': 'Robert Sutherland Lord Papers',
'collection.189_review': 'Robert Sutherland Lord Papers (Review)',
'collection.79': 'Rodef Shalom Congregation Photographs',
'collection.28': 'Rolling Rock Training Camp Ledger',
'collection.134': 'Rose Rand Papers',
'collection.365': 'Royal Kane Photographs',
'collection.135_review': 'Rudolf Carnap Papers (Review)',
'collection.135': 'Rudolf Carnap Papers',
'collection.148': 'Russell H. Heffley Photographs',
'collection.80': 'Rust Engineering Company Records',
'collection.289': 'Samuel A. Musgrave Photographs',
'collection.313': 'Schnabel Company Photographs',
'collection.81': 'Seder Family Photographs',
'collection.334': 'Shadyside Hospital Records',
'collection.299': 'Shooting Star Review',
'collection.299_review': 'Shooting Star Review (Review)',
'collection.82': 'Smoke Control Lantern Slides',
'collection.83': 'Spencer Family Photographs',
'collection.307': 'Squirrel Hill News',
'collection.375': 'St. Luke’s Lutheran Church (West View, Pa.) Records and Photographs',
'collection.136': 'Stalinka: Digital Library of Staliniana',
'collection.136_review': 'Stalinka: Digital Library of Staliniana (Review)',
'collection.211': 'State and Local Government Archives Oral History Collection',
'collection.200': 'Steel Process Lantern Slide Collection',
'collection.111_review': 'Stephen Foster Collection (Review)',
'collection.111': 'Stephen Foster Collection',
'collection.118': 'Stockton Family Letters',
'collection.373': 'Student Life',
'collection.191': 'Szeming Sze Papers',
'collection.338': 'TESTChildren\'s Aid Society of Western Pennsylvania Records',
'collection.84': 'Tax-Book of Pitt Township, Allegheny County, Pa.',
'collection.85': 'Teenie Harris Photographs',
'collection.999': 'Test Collection',
'collection.113_review': 'Thaddeus Sheldon Papers (Review)',
'collection.113': 'Thaddeus Sheldon Papers',
'collection.324': 'The Bulletin, Pittsburg Bulletin, and The Bulletin Index',
'collection.342': 'The McFarland-Hall-Beck Families Papers',
'collection.295': 'Theodore M. Finney Music Library Collection',
'collection.350': 'Thomas C. Brogan Papers on The Mayor\'s Task Force on Civil Disorders',
'collection.319': 'Thomas G. Masaryk Papers',
'collection.319_review': 'Thomas G. Masaryk Papers, 1918-1938  (Review)',
'collection.321': 'Thomas Mellon Galey Photographs',
'collection.321_review': 'Thomas Mellon Galey Photographs (Review)',
'collection.29': 'Thomas Mellon and William B. Negley Day Book',
'collection.270_review': 'Thomas Pownall’s Manuscript Revision of A Topographical Description of the Dominions of the United States of America (Review)',
'collection.270': 'Thomas Pownall’s Manuscript Revision of A Topographical Description of the Dominions of the United States of America',
'collection.382': 'Thorn Hill School for Boys Records ',
'islandora:root': 'Top-level Collection',
'islandora:transformCollection': 'Transform Collection',
'collection.371': 'Tree of Life Congregation Board of Trustees Minute Books',
'collection.88': 'Trimble Company Records',
'collection.253': 'Trinity Church Records Transcript, Volume I',
'collection.253_review': 'Trinity Church Records Transcript, Volume I (Review)',
'collection.90': 'Union Arcade Building Photographs',
'collection.91': 'Union Switch & Signal Strike Photographs',
'collection.89': 'United Electrical, Radio, and Machine Workers of America (UE) Records',
'collection.89_review': 'United Electrical, Radio, and Machine Workers of America (Review)',
'collection.162': 'United Jewish Federation of Greater Pittsburgh Photographs',
'collection.257': 'United States Army 26th Massachusetts Clothing Account Books',
'collection.257_review': 'United States Army 26th Massachusetts Clothing Account Books (Review)',
'collection.316': 'United States Army Corps of Engineers, Pittsburgh District Glass Plate Negatives',
'collection.326': 'University Catalogues',
'collection.325': 'University Times',
'collection.234': 'University of Pittsburgh Archives Audio Recordings Collection',
'collection.215': 'University of Pittsburgh Archives Moving Images Collection',
'collection.282_review': 'University of Pittsburgh Board of Trustees Meeting Minutes (Review)',
'collection.282': 'University of Pittsburgh Board of Trustees Meeting Minutes',
'collection.330': 'University of Pittsburgh Bradford',
'collection.14': 'University of Pittsburgh Greensburg',
'collection.14_review': 'University of Pittsburgh Greensburg (Review)',
'collection.109': 'University of Pittsburgh Historic Photographs',
'collection.109_review': 'University of Pittsburgh Historic Photographs (Review)',
'collection.192': 'University of Pittsburgh Johnstown',
'collection.192_review': 'University of Pittsburgh Johnstown (Review)',
'collection.137_review': 'University of Pittsburgh Press Digital Editions (Review)',
'collection.137': 'University of Pittsburgh Press Digital Editions',
'collection.92': 'Urban League of Pittsburgh Records',
'collection.256_review': 'V.F. Wachsmuth Treatise (Review)',
'collection.256': 'V.F. Wachsmuth Treatise',
'islandora:video_collection': 'Video Collection',
'collection.139': 'Visuals for Foreign Language Instruction',
'collection.138': 'Vézelay: Benedictine Abbey of Sainte Marie Madeleine',
'collection.261': 'W.B. Austen Diary',
'collection.261_review': 'W.B. Austen Diary (Review)',
'collection.93': 'Walter J. Teskey Photographs',
'collection.140': 'Walter and Martha Leuba Papers',
'collection.293': 'Warrantee Atlas of Allegheny County, Pennsylvania',
'collection.141': 'Wesley C. Salmon Papers',
'collection.195': 'Western Pennsylvania Hospital and Dixmont Hospital Records',
'collection.195_review': 'Western Pennsylvania Hospital and Dixmont Hospital Records (Review)',
'collection.97_review': 'Western Pennsylvania Maps (Review)',
'collection.97': 'Western Pennsylvania Maps',
'collection.283': 'Westinghouse Electric Corporation Photographs',
'collection.262_review': 'Whitcomb Meat Market Ledger (Review)',
'collection.262': 'Whitcomb Meat Market Ledger',
'collection.142': 'Wilfrid S. Sellars Papers',
'collection.142_review': 'Wilfrid S. Sellars Papers (Review)',
'collection.255': 'William F. Knox Papers',
'collection.255_review': 'William F. Knox Papers (Review)',
'collection.296': 'William G. Beal Moving Images',
'collection.94': 'William H. Wolf Photographs',
'collection.95': 'William J. Gaughan Collection',
'collection.30': 'William M. Darlington Collection of Fort Pitt Copybooks',
'collection.376': 'William Oetting Collection',
'collection.117': 'William Pitt Family Papers',
'collection.96': 'William V. Winans Jr. Photographs',
'collection.259': 'William and James Scull Survey Ledgers',
'collection.259_review': 'William and James Scull Survey Ledgers (Review)',
'collection.205_review': 'Woman\'s Christian Temperance Union, Wilkinsburg, Pa. Records (Review)',
'collection.205': 'Woman\'s Christian Temperance Union, Wilkinsburg, Pa. Records',
'collection.158_review': 'World War I Trench Maps (Review)',
'collection.158': 'World War I Trench Maps',
'islandora:146': 'testcollection-kmc',
'collection.194_review': 'unknown review collection (Review)',
'collection.181_review': 'unknown review collection (Review)',
},
'site_pid_correction':# Some of the keys represent site IDs that are incorrect
{
'uls-digital-collec': 'uls-digital-collections',
'cumenting-': 'documenting-pitt',
'merican-music': 'american-music',
'm': 'admin',
'sl': ''
},
'site_pid':
{
'uls-digital-collec': 'Default Parent Collection namespace "pitt"',
'cumenting-': 'Documenting Pitt',
'historic-pittsburgh': 'Historic Pittsburgh',
'merican-music': 'American Music',
'm': 'Admin',
'sl': ''
}
}
